name: Publish to maven repository

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  package_and_publish:
    name: Publish to maven repository
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup java SDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    -
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        #passphrase: ${{ secrets.PASSPHRASE }}

    - name: Create bundle and upload to oss.sonatype.org (staging)
      # Fail on first error
      run: |
        set -e
        version=${{ github.event.release.name }}
        artifact=smart-id-java-client-$version
        echo "[INFO] Artifact name: $artifact"
        ./mvnw versions:set -DnewVersion="$version"
        ./mvnw package -DskipTests
        gpg -ab pom.xml
        cd target
        gpg -ab $artifact.jar
        gpg -ab $artifact-sources.jar
        gpg -ab $artifact-javadoc.jar
        jar -cvf bundle.jar ../pom.xml ../pom.xml.asc $artifact.jar $artifact.jar.asc $artifact-javadoc.jar $artifact-javadoc.jar.asc $artifact-sources.jar $artifact-sources.jar.asc
        CODE=$(curl -w "%{http_code}" -o curl_response.txt -s -ujorlina2 -u ${{ secrets.SONATYPEUN }}:${{ secrets.SONATYPEPW }} --request POST -F "file=@bundle.jar" "https://oss.sonatype.org/service/local/staging/bundle_upload")
        echo "[INFO] ------------------------------------------------------------------------"
        echo "[INFO] Upload to oss.sonatype.org ResponseCode: $CODE"
        cat curl_response.txt
        echo -e "\n[INFO] Login to oss.sonatype.org for releasing $artifact"
        echo "[INFO] ------------------------------------------------------------------------"
        [[ $CODE == 201 ]] && exit 0 || exit 1 
        