name: Run tests

on:
  push:
    branches: [ "workflow" ]
  #pull_request:
  #  branches: [ "master" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8']
    name: Run tests with java SDK ${{ matrix.java-version }} on ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Check JAVA version (v${{ matrix.java-version }})
      run: java -version

    - name: Run tests
      # Fail on first error
      run: |
        set -e
        mvn test